#!/usr/bin/env python3
"""Scrape healthcare job listings from naukri.com.

Data source
-----------
naukri.com is a client-rendered Next.js SPA backed by a private JSON API:

    GET https://www.naukri.com/jobapi/v3/search
        ?noOfResults=20&urlType=search_by_keyword&searchType=adv
        &keyword=healthcare and life sciences&pageNo=<N>&sort=f
        &seoKey=healthcare-and-life-sciences-jobs[-N]
    -> {"noOfJobs": 41073, "jobDetails": [ {...}, ... ], "clusters": {...}}

The listing is filtered at the source to the **Healthcare & Life Sciences**
functional area (the `/healthcare-and-life-sciences-jobs` SEO page, ~41k jobs)
and sorted by freshness (`sort=f`, newest first), which lets us stop paginating
once a page is older than the cutoff.

Each jobDetails item carries everything we need directly on the card — no
detail-page fetch required:
    jobId, title, companyName, companyId, currency, createdDate (epoch **ms**),
    jdURL (relative), placeholders[{type: experience|salary|location}],
    salaryDetail{minimumSalary, maximumSalary, currency, hideSalary},
    minimumExperience, maximumExperience, tagsAndSkills, jobDescription (short),
    roleCategoryGid, consultant, hiringFor, clientTitleString, logoPathV3.

Why browser-captured JSON (not live HTTP)
-----------------------------------------
The `/jobapi/v3/search` endpoint requires a per-request signed `nkparam`
header generated by the site's own JavaScript; requests without it return
HTTP 406 {"message": "recaptcha required"}. The whole site also sits behind
Akamai, which resets non-browser TLS fingerprints. So — exactly like this
repo's `indeed/` scraper — the responses are captured in a real browser
(paging through the date-sorted listing while a fetch/XHR interceptor
accumulates `jobDetails`), dumped to `captures/<DD-MM-YYYY>.json`, and this
scraper consumes that JSON offline. See README.md for the capture recipe.

robots.txt (checked against the saved capture, honored per master-spec §7):
the `User-agent: *` group does NOT disallow the healthcare listing or
`/jobapi/`; only recruiter/admin paths are blocked. naukri additionally
disallows automated AI crawlers (`claudebot`, `gptbot`, …) from `/` — we do
not crawl as a bot; a human drives the browser capture, and this script only
transforms the already-captured JSON.

Salary (master spec §3: capture, don't filter)
----------------------------------------------
naukri salaries are INR per annum. `salaryDetail` holds the full integer
range (e.g. 4,500,000); the card's salary placeholder ("45-60 Lacs PA") is
kept verbatim as salary_raw. Undisclosed -> "Not Disclosed", numeric fields
empty. Never filtered on, never invented.

Classification (taxonomy-migration-spec, 2026-08-25)
----------------------------------------------------
Every candidate card goes through the shared two-level classifier
(_shared/classification.py :: classify_job): out-of-scope cards are dropped
and counted as excluded_out_of_scope; in-scope cards get `category`
("Non Clinical" | "Public Health"), `sub_category`, and the role_family /
score trace columns in the rich CSV. needs_review rows are kept AND appended
to needs_review.csv.

Outputs (per the repo README + master-scraper-spec.md)
------------------------------------------------------
* naukri_roles_jobs.csv      — rich cumulative store (dedup key: job_id),
                               source of truth for the incremental watermark.
* ../../jobs_csv/<DD-MM-YYYY>/naukri_roles.csv
                             — the same jobs mapped to the shared
                               HealthCareers.club 23-column schema
                               (CLUB_COLUMNS from _shared/classification.py).
* needs_review.csv           — in-scope titles flagged by the classifier.

Time window: first run keeps jobs posted in the last INITIAL_WINDOW_DAYS (2)
(7); later runs keep only jobs newer than the newest stored posted_date
minus WATERMARK_GRACE_DAYS of overlap (dedup absorbs the overlap).

Run `python naukri_scraper.py --help` for options.
"""

import argparse
import html as html_lib
import json
import logging
import re
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import pandas as pd

import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                os.pardir, "_shared"))
from classification import classify_job, extract_qualification, CLUB_COLUMNS

# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------

SITE = "naukri_roles"
SITE_BASE = "https://www.naukri.com"
# The source-side healthcare filter: the "Healthcare & Life Sciences"
# functional-area SEO listing, date-sorted. Documented for the capture step.
LISTING_URL = SITE_BASE + "/healthcare-and-life-sciences-jobs?sort=f"

# First run keeps the last 7 days (master spec §4 default); later runs use the
# watermark. naukri posts hundreds of healthcare jobs/day, so this stays tight.
# First-run window, narrowed from the master spec §4 default of 7 to 2 to
# match the rest of the re-scoped fleet. Later runs use the watermark.
INITIAL_WINDOW_DAYS = 2
WATERMARK_GRACE_DAYS = 2

DESCRIPTION_MAX_CHARS = 12_000

HERE = Path(__file__).resolve().parent
RICH_CSV = str(HERE / "naukri_roles_jobs.csv")
NEEDS_REVIEW_CSV = str(HERE / "needs_review.csv")
CAPTURES_DIR = HERE / "captures"
# jobs_csv/ lives at the repo root, two levels up from scrappers/naukri/.
CLUB_CSV_DIR = HERE.resolve().parents[1] / "jobs_csv"

# Rich (source-of-truth) columns — superset, keeps everything the card gives.
RICH_COLUMNS = [
    "source", "job_id", "title", "company", "company_id", "hiring_for",
    "city", "country", "country_code", "country_dial_code", "salary_raw",
    "salary_min", "salary_max", "salary_currency", "salary_period",
    "experience_min_years", "experience_max_years", "job_type", "category",
    "sub_category", "sub_category_basis", "role_family",
    "all_families", "family_scores", "family_confidence", "matched_in",
    "needs_review",
    "company_type", "role_category_gid", "tags_and_skills", "vacancies",
    "company_logo", "posted_date", "description", "job_url", "scraped_at",
]

# The club CSV contract is the shared 23-column CLUB_COLUMNS imported from
# _shared/classification.py — never hand-copied here.

# naukri is India-first, but the healthcare listing carries some overseas
# postings whose location placeholder is a bare country name. Map those; every
# other (Indian city) location defaults to India.
COUNTRY_META = {
    "india": ("India", "IN", "+91"),
    "united arab emirates": ("United Arab Emirates", "AE", "+971"),
    "uae": ("United Arab Emirates", "AE", "+971"),
    "dubai": ("United Arab Emirates", "AE", "+971"),
    "abu dhabi": ("United Arab Emirates", "AE", "+971"),
    "saudi arabia": ("Saudi Arabia", "SA", "+966"),
    "qatar": ("Qatar", "QA", "+974"),
    "kuwait": ("Kuwait", "KW", "+965"),
    "bahrain": ("Bahrain", "BH", "+973"),
    "oman": ("Oman", "OM", "+968"),
    "germany": ("Germany", "DE", "+49"),
    "united kingdom": ("United Kingdom", "GB", "+44"),
    "ireland": ("Ireland", "IE", "+353"),
    "singapore": ("Singapore", "SG", "+65"),
    "malaysia": ("Malaysia", "MY", "+60"),
    "maldives": ("Maldives", "MV", "+960"),
    "nepal": ("Nepal", "NP", "+977"),
    "united states": ("United States", "US", "+1"),
    "usa": ("United States", "US", "+1"),
    "canada": ("Canada", "CA", "+1"),
    "australia": ("Australia", "AU", "+61"),
}

log = logging.getLogger("naukri_scraper")

# ----------------------------------------------------------------------------
# Field parsing / classification
# ----------------------------------------------------------------------------

_TAG_RE = re.compile(r"<[^>]+>")


def strip_html(text):
    """HTML / multiline card text -> readable single-spaced text."""
    text = re.sub(r"</?(p|br|li|ul|ol|div|h\d)[^>]*>", " ", text or "",
                  flags=re.IGNORECASE)
    text = _TAG_RE.sub("", text)
    text = html_lib.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def epoch_ms_to_date(epoch_ms):
    """Unix epoch in MILLISECONDS -> "YYYY-MM-DD" (UTC), or "" if unparseable.

    naukri stamps createdDate in ms; 0/None (a handful of cards) -> "".
    """
    try:
        ms = int(epoch_ms)
    except (TypeError, ValueError):
        return ""
    if ms <= 0:
        return ""
    try:
        return datetime.fromtimestamp(ms / 1000, tz=timezone.utc).date().isoformat()
    except (ValueError, OSError, OverflowError):
        return ""


def placeholder(job, kind):
    """Return the label of the placeholder of the given type, or ""."""
    for p in job.get("placeholders") or []:
        if p.get("type") == kind:
            return (p.get("label") or "").strip()
    return ""


_CITY_ALL_AREAS_RE = re.compile(r"\s*\(all areas\)\s*", re.IGNORECASE)


def parse_location(location):
    """Split a naukri location placeholder into (city, country_name, code, dial).

    Formats seen: "Hyderabad", "Nashik, Pune, Mumbai (All Areas)" (multi-city
    -> take the first), "Saudi Arabia" (a bare country). Unknown -> India.
    """
    location = (location or "").strip()
    if not location:
        return ("", "India", "IN", "+91")
    first = location.split(",")[0].strip()
    first = _CITY_ALL_AREAS_RE.sub("", first).strip()

    # A bare country name as the whole location (overseas postings).
    meta = COUNTRY_META.get(location.lower()) or COUNTRY_META.get(first.lower())
    if meta and first.lower() in COUNTRY_META:
        # location itself names a country -> no city given; use the country
        # name as the city too (club requires city_name non-empty), matching
        # the naukrigulf "Qatar -> Qatar" convention.
        name, code, dial = meta
        return (name, name, code, dial)
    if meta:
        name, code, dial = meta
        return (first, name, code, dial)
    # Default: an Indian city.
    return (first, "India", "IN", "+91")


def parse_salary(job):
    """Return (salary_raw, min_int, max_int, currency, period).

    naukri salaries are INR per annum. `salaryDetail` holds full integers;
    the salary placeholder ("45-60 Lacs PA") is the verbatim display. Hidden
    / absent -> ("Not Disclosed", "", "", "", "").
    """
    raw = placeholder(job, "salary") or ""
    detail = job.get("salaryDetail") or {}
    if not detail or detail.get("hideSalary"):
        return (raw or "Not Disclosed", "", "", "", "")
    lo = detail.get("minimumSalary")
    hi = detail.get("maximumSalary")
    try:
        lo = int(round(float(lo))) if lo not in (None, "") else None
        hi = int(round(float(hi))) if hi not in (None, "") else None
    except (TypeError, ValueError):
        lo = hi = None
    if not lo and not hi:
        return (raw or "Not Disclosed", "", "", "", "")
    if lo and hi and hi < lo:
        lo, hi = hi, lo
    lo = lo or hi
    hi = hi or lo
    currency = (detail.get("currency") or job.get("currency") or "INR").upper()
    # naukri displays annual figures ("... PA"); default per_annum.
    period = "per_month" if re.search(r"\bp\.?m\b|month", raw, re.IGNORECASE) \
        else "per_annum"
    return (raw or "Not Disclosed", str(lo), str(hi), currency, period)


def _exp_int(value):
    try:
        return str(int(float(value)))
    except (TypeError, ValueError):
        return ""


# All keep/drop and category labeling is classify_job's alone
# (_shared/classification.py) — no per-scraper classification lists here.
_PHARMA_COMPANY_RE = re.compile(
    r"pharma|therapeut|laborator|\blabs?\b|\bcro\b|biotech|life ?science|"
    r"diagnostic|clinical research|medical devices?|healthcare it|"
    r"health informatics", re.IGNORECASE)


def classify_company_type(name, hiring_for=""):
    """club company_type enum: hospital | pharma (default hospital)."""
    text = "{} {}".format(name or "", hiring_for or "")
    return "pharma" if _PHARMA_COMPANY_RE.search(text) else "hospital"


def map_job_type(job):
    """club job_type enum. naukri cards rarely mark WFH on the listing; use the
    title/tags and jobType hint, defaulting to full_time."""
    text = " ".join(str(job.get(k) or "") for k in
                    ("title", "tagsAndSkills", "jobType")).lower()
    if "work from home" in text or "wfh" in text or "remote" in text:
        return "remote"
    if "hybrid" in text:
        return "hybrid"
    if "part time" in text or "part-time" in text:
        return "part_time"
    return "full_time"


# ----------------------------------------------------------------------------
# Row building
# ----------------------------------------------------------------------------

def real_company(job):
    """The displayed hiring entity. For consultant postings that don't hide the
    client, prefer the client name; else the posting company."""
    company = (job.get("companyName") or "").strip()
    if job.get("consultant") and not job.get("hideClientName"):
        client = (job.get("clientTitleString") or job.get("hiringFor") or "").strip()
        if client:
            return company, client       # (recruiter, client)
    return company, ""


def job_to_rich_row(job):
    """Build one rich-CSV row from a captured jobDetails card.

    Returns None when the shared classifier rules the job out of scope
    (the caller counts it as excluded_out_of_scope and drops it).
    """
    title = (job.get("title") or "").strip()
    company, hiring_for = real_company(job)
    city, country, code, dial = parse_location(placeholder(job, "location"))
    verdict = classify_job(
        title,
        job.get("tagsAndSkills") or "",
        strip_html(job.get("jobDescription") or ""))
    if not verdict["in_scope"]:
        return None
    salary_raw, sal_min, sal_max, sal_cur, sal_per = parse_salary(job)
    jd_url = (job.get("jdURL") or "").strip()
    if jd_url.startswith("/"):
        jd_url = SITE_BASE + jd_url

    return {
        "source": SITE,
        "job_id": str(job.get("jobId") or ""),
        "title": title,
        "company": company,
        "company_id": str(job.get("companyId") or ""),
        "hiring_for": hiring_for,
        "city": city,
        "country": country,
        "country_code": code,
        "country_dial_code": dial,
        "salary_raw": salary_raw,
        "salary_min": sal_min,
        "salary_max": sal_max,
        "salary_currency": sal_cur,
        "salary_period": sal_per,
        "experience_min_years": _exp_int(job.get("minimumExperience")),
        "experience_max_years": _exp_int(job.get("maximumExperience")),
        "job_type": map_job_type(job),
        "category": verdict["category"],
        "sub_category": verdict["sub_category"],
        "sub_category_basis": verdict["sub_category_basis"],
        "role_family": verdict["role_family"],
        "company_type": classify_company_type(company, hiring_for),
        "role_category_gid": str(job.get("roleCategoryGid") or ""),
        "tags_and_skills": (job.get("tagsAndSkills") or "").strip(),
        "vacancies": str(job.get("vacancy") or ""),
        "company_logo": (job.get("logoPathV3") or job.get("logoPath") or "").strip(),
        "posted_date": epoch_ms_to_date(job.get("createdDate")),
        "description": strip_html(job.get("jobDescription") or "")[:DESCRIPTION_MAX_CHARS],
        "job_url": jd_url,
        "scraped_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "needs_review": "true" if verdict["needs_review"] else "false",
        "all_families": verdict["all_families"],
        "family_scores": verdict["family_scores"],
        "family_confidence": verdict["family_confidence"],
        "matched_in": verdict["matched_in"],
    }


def _clean(value):
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    text = str(value).strip()
    return "" if text.lower() == "nan" else text


def rich_row_to_club_row(r):
    """Map a rich row to the 23-column HealthCareers.club schema.

    The club salary_currency enum only allows INR/USD, so salary is exported
    only when the source currency matches AND the pay period is known;
    otherwise those columns stay empty (the rich CSV keeps the raw values).
    """
    currency = _clean(r.get("salary_currency")).upper()
    period = _clean(r.get("salary_period"))
    lo, hi = _clean(r.get("salary_min")), _clean(r.get("salary_max"))
    exportable = bool(lo) and currency in ("INR", "USD") and period != ""
    return {
        "country_name": _clean(r.get("country")) or "India",
        "country_code": _clean(r.get("country_code")) or "IN",
        "country_dial_code": _clean(r.get("country_dial_code")) or "+91",
        "city_name": _clean(r.get("city")) or _clean(r.get("country")) or "India",
        "company_name": _clean(r.get("company")),
        "company_type": _clean(r.get("company_type")) or "hospital",
        "company_logo": _clean(r.get("company_logo")),
        "company_about": "",
        "title": _clean(r.get("title")),
        "description": _clean(r.get("description")),
        "job_type": _clean(r.get("job_type")) or "full_time",
        "category": _clean(r.get("category")),
        "sub_category": _clean(r.get("sub_category")),
        "role_family": _clean(r.get("role_family")),
        "application_url": _clean(r.get("job_url")),
        "posted_at": _clean(r.get("posted_date")),
        "min_experience": _clean(r.get("experience_min_years")),
        "max_experience": _clean(r.get("experience_max_years")),
        # naukri cards carry no structured qualification field, so this is
        # always grounded extraction from the description (never inferred).
        "qualification": extract_qualification(_clean(r.get("description"))),
        "min_salary": lo if exportable else "",
        "max_salary": (hi or lo) if exportable else "",
        "salary_period": period if exportable else "",
        "salary_currency": currency if exportable else "",
    }


# ----------------------------------------------------------------------------
# Time window
# ----------------------------------------------------------------------------

def compute_cutoff(existing_df, today=None):
    """First run: today - INITIAL_WINDOW_DAYS. Later: newest stored posted_date
    minus WATERMARK_GRACE_DAYS of overlap (dedup absorbs it)."""
    if existing_df is not None and "posted_date" in existing_df.columns:
        dates = pd.to_datetime(existing_df["posted_date"], errors="coerce").dropna()
        if not dates.empty:
            return (dates.max() - pd.Timedelta(days=WATERMARK_GRACE_DAYS)).date().isoformat()
    today = today or date.today()
    return (today - timedelta(days=INITIAL_WINDOW_DAYS)).isoformat()


# ----------------------------------------------------------------------------
# Capture loading
# ----------------------------------------------------------------------------

def load_capture(path):
    """Load a browser capture: either a bare JSON array of jobDetails cards, or
    a full search-API response ({"jobDetails": [...]}), or a list of such
    responses. Returns a de-duplicated list of card dicts."""
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)

    cards = []
    if isinstance(data, dict):
        cards = data.get("jobDetails") or []
    elif isinstance(data, list):
        if data and isinstance(data[0], dict) and "jobDetails" in data[0]:
            for page in data:
                cards.extend(page.get("jobDetails") or [])
        else:
            cards = data
    by_id = {}
    for c in cards:
        jid = str(c.get("jobId") or "")
        if jid:
            by_id.setdefault(jid, c)
    return list(by_id.values())


def latest_capture():
    """Newest captures/<DD-MM-YYYY>.json by embedded date, or None."""
    if not CAPTURES_DIR.exists():
        return None
    candidates = sorted(CAPTURES_DIR.glob("*.json"))
    return str(candidates[-1]) if candidates else None


def load_existing(path):
    try:
        return pd.read_csv(path, dtype=str)
    except FileNotFoundError:
        return None


def write_club_csv(rich_df, run_date):
    club_rows = [rich_row_to_club_row(r) for _, r in rich_df.iterrows()]
    club_df = pd.DataFrame(club_rows, columns=CLUB_COLUMNS)
    out_dir = CLUB_CSV_DIR / run_date
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "{}.csv".format(SITE)
    club_df.to_csv(target, index=False)
    return target, len(club_df)


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Scrape healthcare jobs from a naukri.com browser capture.")
    parser.add_argument("--from-json", dest="from_json", default=None,
                        metavar="FILE",
                        help="capture JSON to ingest (default: newest in "
                             "captures/)")
    parser.add_argument("--output", default=RICH_CSV,
                        help="rich cumulative CSV path (default: %(default)s)")
    parser.add_argument("--limit", type=int, default=None, metavar="N",
                        help="stop after N new jobs (for test runs)")
    parser.add_argument("--run-date", default=date.today().strftime("%d-%m-%Y"),
                        help="jobs_csv/<DD-MM-YYYY>/ folder (default: today)")
    parser.add_argument("--verbose", action="store_true", help="debug logging")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s", datefmt="%H:%M:%S")

    capture_path = args.from_json or latest_capture()
    if not capture_path or not Path(capture_path).exists():
        parser.error("no capture JSON found — pass --from-json <file> "
                     "(see README for the browser-capture recipe)")
    cards = load_capture(capture_path)
    log.info("Loaded %d unique cards from %s", len(cards), capture_path)

    existing_df = load_existing(args.output)
    known_ids = set(existing_df["job_id"].dropna()) if existing_df is not None else set()
    cutoff = compute_cutoff(existing_df)
    log.info("Existing CSV has %d known jobs; keeping jobs posted on/after %s",
             len(known_ids), cutoff)

    counters = {"scanned": 0, "excluded_old": 0, "excluded_out_of_scope": 0,
                "needs_review": 0,
                "new": 0, "duplicates": 0}
    new_rows, review_log = [], []

    for job in cards:
        counters["scanned"] += 1
        try:
            job_id = str(job.get("jobId") or "")
            posted = epoch_ms_to_date(job.get("createdDate"))
            if not (posted and posted >= cutoff):
                counters["excluded_old"] += 1
                continue
            if job_id in known_ids:
                counters["duplicates"] += 1
                continue
            row = job_to_rich_row(job)
            if row is None:
                counters["excluded_out_of_scope"] += 1
                continue
        except Exception as exc:  # never let one card crash the run
            log.warning("Skipping malformed card %s: %s", job.get("jobId"), exc)
            continue

        if row["needs_review"] == "true":
            counters["needs_review"] += 1
            review_log.append({"job_id": row["job_id"], "title": row["title"],
                               "company": row["company"]})
        known_ids.add(row["job_id"])
        new_rows.append(row)
        counters["new"] += 1
        if args.limit is not None and counters["new"] >= args.limit:
            break

    # ---- write rich cumulative CSV (source of truth) ----
    if new_rows:
        new_df = pd.DataFrame(new_rows, dtype=str)
        combined = (pd.concat([existing_df, new_df], ignore_index=True)
                    if existing_df is not None else new_df)
        combined = combined.drop_duplicates(subset="job_id", keep="first")
        for col in RICH_COLUMNS:
            if col not in combined.columns:
                combined[col] = ""
        combined = combined[RICH_COLUMNS]
        combined.to_csv(args.output, index=False)
        log.info("Wrote %s (%d total rows)", args.output, len(combined))
    else:
        combined = existing_df if existing_df is not None else pd.DataFrame(columns=RICH_COLUMNS)
        log.info("No new jobs; %s left unchanged", args.output)

    # ---- always (re)write the club-schema CSV for this run date ----
    if len(combined):
        target, n = write_club_csv(combined, args.run_date)
        log.info("Wrote %s (%d rows, HealthCareers.club schema)", target, n)

    if review_log:
        review_df = pd.DataFrame(review_log, dtype=str)
        try:
            old_review = pd.read_csv(NEEDS_REVIEW_CSV, dtype=str)
            review_df = pd.concat([old_review, review_df], ignore_index=True)
        except FileNotFoundError:
            pass
        review_df = review_df.drop_duplicates(subset="job_id", keep="first")
        review_df.to_csv(NEEDS_REVIEW_CSV, index=False)
        log.info("Wrote %s (%d titles to review)", NEEDS_REVIEW_CSV, len(review_df))

    print("\n===== Run summary =====")
    print("Cards scanned:            {:>5,}".format(counters["scanned"]))
    print("Excluded (older than {}): {:>3,}".format(cutoff, counters["excluded_old"]))
    print("Excluded (out of scope):  {:>5,}".format(counters["excluded_out_of_scope"]))
    print("Flagged needs_review:     {:>5,}".format(counters["needs_review"]))
    print("New jobs added:           {:>5,}".format(counters["new"]))
    print("Duplicates skipped:       {:>5,}".format(counters["duplicates"]))


if __name__ == "__main__":
    main()
